image: node:14

services:
    - name: 'docker.elastic.co/elasticsearch/elasticsearch:7.15.2'
      alias: 'elasticsearch'
      command: ['bin/elasticsearch', '-Expack.security.enabled=false', '-Ediscovery.type=single-node']

variables:
    CI: 'true'

test_app:
    script:
        - npm ci
        - npm run install:app
        - npm run build:app

test_server:
    script:
        - npm install
        - npm run transpile:prod
        - npm run coverage:silent
    after_script:
        - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN -f ./coverage/coverage-final.json