stages:
  - build
  - docker_latest

default:
  image: node:16
  services:
    - name: "docker.elastic.co/elasticsearch/elasticsearch:latest"
      alias: "elasticsearch"
      command:
        ["bin/elasticsearch", "-Expack.security.enabled=false", "-Ediscovery.type=single-node"]
      variables:
        ES_JAVA_OPTS: "-Xms200m -Xmx400m"

variables:
  CI: "true"

app:
  stage: build
  only:
    refs:
      - dev
      - "merge_requests"
  script:
    - npm ci
    - npm run install:app
    - npm run build:app

server:
  stage: build
  only:
    refs:
      - dev
      - "merge_requests"
  script:
    - npm install
    - npm run transpile:prod
    - npm run coverage:silent
  #after_script:
  #    - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN -f ./coverage/coverage-final.json
  
release_docker_latest:
  stage: docker_latest
  only:
    refs:
      - dev
  script:
    - docker build . -t boi12321/porn-vault:edge -f docker/Dockerfile.debian
    - docker login -u boi12321 -p $DOCKER_TOKEN
    - docker push boi12321/porn-vault:edge

