image: node:14

services:
    - elasticsearch:latest

variables:
    CI: "true"

test_app:
    script:
        - npm ci
        - npm run install:app
        - npm run build:app

test_server:
    before_script:
        - sudo swapoff -a
        - sudo sysctl -w vm.swappiness=1
        - sudo sysctl -w fs.file-max=262144
        - sudo sysctl -w vm.max_map_count=262144
    script:
        - npm install
        - npm run transpile:prod
        - npm run coverage:silent
    after_script:
        - bash <(curl -s https://codecov.io/bash)